name: simple_auth
description: Simple Auth is the simplest way to authenticate your users/apis.
version: 2.0.10
homepage: https://github.com/clancey/simple_auth

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.1.2
  http: ^0.13.3
  crypto: ^3.0.1

dev_dependencies:
  test: ^1.17.4
