name: simple_auth
description: Simple Auth is the simplest way to authenticate your users/apis.
version: 2.0.5
author: James Clancey <james.clancey@gmail.com>
homepage: https://github.com/clancey/simple_auth

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  http: '>=0.11.0 <0.13.0'
  meta: ^1.1.2

dev_dependencies:
  test: ^1.3.0
